# Welcome to Minecraft Mondays!
# -----------------------------

# The URL which will accept or decline users.
url: https://example.com/api/games/bindings/guild/500612695570120704/game/minecraft/id/
token: abcdefg==
kick: true
webhook: null

message:
  header: |+
    &f&lWelcome to Comp&4&lSoc&r
    &7&oRoyal Holloway, University of London&r&f

  footer: |-
    &r
    &7Discord: &fhttps://dc.cmpsc.uk/
    &7Website: &fhttps://computingsociety.co.uk/
  kick:
    MISSING_URI: |
      The MondayWhitelist plugin was not provided a whitelist URL
    MALFORMED_URI: |
      The MondayWhitelist plugin was provided an invalid URL
    ALLOWED: |
      Welcome!
    NOT_WHITELISTED: |
      Please add yourself (or get your RHUL friend to add you) to the whitelist with the CompSoc Passport.

      Log in > Guilds > RHUL Computing Society > Manage Game Connections
      https://passport.cmpsc.uk/
    BANNED: |
      You have been banned by the Computing Society
    SERVER_ERROR: |
      The MondayWhitelist server encountered an error
    SERVER_UNAUTHORISED: |
      The MondayWhitelist client was unauthorized by the MondayWhitelist server
    SERVER_FORBIDDEN: |
      The MondayWhitelist client was unauthorized by the MondayWhitelist server
    BAD_RESPONSE: |
      The MondayWhitelist client recieved a bad response from the MondayWhitelist server
    IO_EXCEPTION: |
      An IOException was caught while trying to fetch your whitelist details
    UNCAUGHT_EXCEPTION: |
      An uncaught exception was caught while trying to fetch your whitelist details
  join:
    MISSING_URI: |
      The MondayWhitelist plugin was not provided a whitelist URL
    MALFORMED_URI: |
      The MondayWhitelist plugin was provided an invalid URL
    ALLOWED: |
      Have a nice day!
    NOT_WHITELISTED: |
      The server will soon be for whitelisted members only.
      Whitelist you or a friend at https://passport.cmpsc.uk/
    BANNED: |
      You have been banned by the Computing Society
    SERVER_ERROR: |
      The MondayWhitelist server encountered an error
    SERVER_UNAUTHORISED: |
      The MondayWhitelist client was unauthorized by the MondayWhitelist server
    SERVER_FORBIDDEN: |
      The MondayWhitelist client was unauthorized by the MondayWhitelist server
    BAD_RESPONSE: |
      The MondayWhitelist client recieved a bad response from the MondayWhitelist server
    IO_EXCEPTION: |
      An IOException was caught while trying to fetch your whitelist details
    UNCAUGHT_EXCEPTION: |
      An uncaught exception was caught while trying to fetch your whitelist details
